### ISSUE TITLE
Unexpected error fetching sensor data: invalid literal for int() with base 10: 'name'

### ISSUE THREAD

**Issue by HengeDK** [J-Lindvig/Pollen_DK#1]
Får følgende fejl, har prøvet at fjerne og installer igen
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
Pollen_DK v0.2

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/pollen_dk/sensor.py", line 32, in async_update_data
    await hass.async_add_executor_job(pollen_DK.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pollen_dk/pollen_dk_api.py", line 32, in update
    if int(regionID) in self._regionIDs:
ValueError: invalid literal for int() with base 10: 'name'

**Comment by J-Lindvig** [comment]
The API at https://www.astma-allergi.dk  have had at change in the datastructure.

I have now changed my API client to mirror these changes and the integration is now working again.
